// spotless:off
package frc.robot.util.choreo;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
// If the 2 imports above cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj LeftBumpToDepot = new ChoreoTraj(
        "LeftBumpToDepot",
        OptionalInt.empty(),
        2.39204,
        new Pose2d(3.58204, 6.03649, Rotation2d.fromRadians(3.14159)),
        new Pose2d(1.0858, 5.9692, Rotation2d.fromRadians(3.14159))
    );
    public static final ChoreoTraj RightClimb = new ChoreoTraj(
        "RightClimb",
        OptionalInt.empty(),
        3.92861,
        new Pose2d(3.58204, 2.03271, Rotation2d.fromRadians(3.14159)),
        new Pose2d(1.0534, 2.9572, Rotation2d.fromRadians(-1.5708))
    );
    public static final ChoreoTraj DepotToLeftClimb = new ChoreoTraj(
        "DepotToLeftClimb",
        OptionalInt.empty(),
        3.40867,
        new Pose2d(1.0858, 5.9692, Rotation2d.fromRadians(1.5708)),
        new Pose2d(1.0534, 4.306, Rotation2d.fromRadians(1.5708))
    );
    public static final ChoreoTraj LeftBumpToDepotPartial = new ChoreoTraj(
        "LeftBumpToDepotPartial",
        OptionalInt.empty(),
        2.4277,
        new Pose2d(2.66764, 6.03649, Rotation2d.fromRadians(3.14159)),
        new Pose2d(1.0858, 5.9692, Rotation2d.fromRadians(3.14159))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
        Map.entry("LeftBumpToDepot", LeftBumpToDepot),
        Map.entry("RightClimb", RightClimb),
        Map.entry("DepotToLeftClimb", DepotToLeftClimb),
        Map.entry("LeftBumpToDepotPartial", LeftBumpToDepotPartial)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
// spotless:on
