
package frc.robot.util.choreo;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj DepotToLeftClimb_BLUE = new ChoreoTraj(
	    "DepotToLeftClimb_BLUE",
	    OptionalInt.empty(),
	    3.28771,
	    new Pose2d(1.086, 5.969, Rotation2d.fromRadians(1.571)),
	    new Pose2d(1.053, 4.306, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj DepotToLeftClimb_RED = new ChoreoTraj(
	    "DepotToLeftClimb_RED",
	    OptionalInt.empty(),
	    3.28771,
	    new Pose2d(1.086, 5.969, Rotation2d.fromRadians(1.571)),
	    new Pose2d(1.053, 4.306, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj LeftBumpToDepotPartial_BLUE = new ChoreoTraj(
	    "LeftBumpToDepotPartial_BLUE",
	    OptionalInt.empty(),
	    2.33346,
	    new Pose2d(2.668, 6.036, Rotation2d.fromRadians(3.142)),
	    new Pose2d(1.086, 5.969, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj LeftBumpToDepotPartial_RED = new ChoreoTraj(
	    "LeftBumpToDepotPartial_RED",
	    OptionalInt.empty(),
	    2.33346,
	    new Pose2d(2.668, 6.036, Rotation2d.fromRadians(3.142)),
	    new Pose2d(1.086, 5.969, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj LeftBumpToDepot_BLUE = new ChoreoTraj(
	    "LeftBumpToDepot_BLUE",
	    OptionalInt.empty(),
	    2.24906,
	    new Pose2d(3.582, 6.036, Rotation2d.fromRadians(3.142)),
	    new Pose2d(1.086, 5.969, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj LeftBumpToDepot_RED = new ChoreoTraj(
	    "LeftBumpToDepot_RED",
	    OptionalInt.empty(),
	    2.24906,
	    new Pose2d(3.582, 6.036, Rotation2d.fromRadians(3.142)),
	    new Pose2d(1.086, 5.969, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj LeftShootToNZ_BLUE = new ChoreoTraj(
	    "LeftShootToNZ_BLUE",
	    OptionalInt.empty(),
	    2.83723,
	    new Pose2d(3.233, 7.502, Rotation2d.fromRadians(0)),
	    new Pose2d(6.908, 3.961, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj LeftShootToNZ_RED = new ChoreoTraj(
	    "LeftShootToNZ_RED",
	    OptionalInt.empty(),
	    2.83723,
	    new Pose2d(3.233, 7.502, Rotation2d.fromRadians(0)),
	    new Pose2d(6.908, 3.961, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj LeftTrenchToNZ_BLUE = new ChoreoTraj(
	    "LeftTrenchToNZ_BLUE",
	    OptionalInt.empty(),
	    4.12622,
	    new Pose2d(4.476, 7.596, Rotation2d.fromRadians(3.142)),
	    new Pose2d(7.928, 5.476, Rotation2d.fromRadians(-1.833))
	);
	public static final ChoreoTraj LeftTrenchToNZ_RED = new ChoreoTraj(
	    "LeftTrenchToNZ_RED",
	    OptionalInt.empty(),
	    4.12622,
	    new Pose2d(4.476, 7.596, Rotation2d.fromRadians(3.142)),
	    new Pose2d(7.928, 5.476, Rotation2d.fromRadians(-1.833))
	);
	public static final ChoreoTraj MiddleNZToShoot_BLUE = new ChoreoTraj(
	    "MiddleNZToShoot_BLUE",
	    OptionalInt.empty(),
	    2.31795,
	    new Pose2d(7.928, 5.476, Rotation2d.fromRadians(-1.833)),
	    new Pose2d(3.233, 7.502, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj MiddleNZToShoot_RED = new ChoreoTraj(
	    "MiddleNZToShoot_RED",
	    OptionalInt.empty(),
	    2.31795,
	    new Pose2d(7.928, 5.476, Rotation2d.fromRadians(-1.833)),
	    new Pose2d(3.233, 7.502, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RightClimb_BLUE = new ChoreoTraj(
	    "RightClimb_BLUE",
	    OptionalInt.empty(),
	    3.74987,
	    new Pose2d(3.582, 2.033, Rotation2d.fromRadians(3.142)),
	    new Pose2d(1.053, 2.957, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj RightClimb_RED = new ChoreoTraj(
	    "RightClimb_RED",
	    OptionalInt.empty(),
	    3.74987,
	    new Pose2d(3.582, 2.033, Rotation2d.fromRadians(3.142)),
	    new Pose2d(1.053, 2.957, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj MiddleNZToLeftClimb = new ChoreoTraj(
	    "MiddleNZToLeftClimb",
	    OptionalInt.empty(),
	    4.45586,
	    new Pose2d(7.928, 5.476, Rotation2d.fromRadians(-1.833)),
	    new Pose2d(1.053, 4.306, Rotation2d.fromRadians(1.571))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("DepotToLeftClimb_BLUE", DepotToLeftClimb_BLUE),
		Map.entry("DepotToLeftClimb_RED", DepotToLeftClimb_RED),
		Map.entry("LeftBumpToDepotPartial_BLUE", LeftBumpToDepotPartial_BLUE),
		Map.entry("LeftBumpToDepotPartial_RED", LeftBumpToDepotPartial_RED),
		Map.entry("LeftBumpToDepot_BLUE", LeftBumpToDepot_BLUE),
		Map.entry("LeftBumpToDepot_RED", LeftBumpToDepot_RED),
		Map.entry("LeftShootToNZ_BLUE", LeftShootToNZ_BLUE),
		Map.entry("LeftShootToNZ_RED", LeftShootToNZ_RED),
		Map.entry("LeftTrenchToNZ_BLUE", LeftTrenchToNZ_BLUE),
		Map.entry("LeftTrenchToNZ_RED", LeftTrenchToNZ_RED),
		Map.entry("MiddleNZToShoot_BLUE", MiddleNZToShoot_BLUE),
		Map.entry("MiddleNZToShoot_RED", MiddleNZToShoot_RED),
		Map.entry("RightClimb_BLUE", RightClimb_BLUE),
		Map.entry("RightClimb_RED", RightClimb_RED),
		Map.entry("MiddleNZToLeftClimb", MiddleNZToLeftClimb)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
