// spotless:off
package frc.robot.util.choreo;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
// If the 2 imports above cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj DepotIntakeToClimb_BLUE = new ChoreoTraj(
        "DepotIntakeToClimb_BLUE",
        OptionalInt.empty(),
        1.07255,
        new Pose2d(0.54124, 4.9616, Rotation2d.fromRadians(-1.8326)),
        new Pose2d(1.0788, 4.9, Rotation2d.fromRadians(1.5708))
    );
    public static final ChoreoTraj DepotIntakeToClimb_RED = new ChoreoTraj(
        "DepotIntakeToClimb_RED",
        OptionalInt.empty(),
        1.07255,
        new Pose2d(0.54124, 4.9616, Rotation2d.fromRadians(-1.8326)),
        new Pose2d(1.0788, 4.9, Rotation2d.fromRadians(1.5708))
    );
    public static final ChoreoTraj DepotIntake_BLUE = new ChoreoTraj(
        "DepotIntake_BLUE",
        OptionalInt.empty(),
        4.5751,
        new Pose2d(0.54124, 7.4, Rotation2d.fromRadians(-1.8326)),
        new Pose2d(0.54124, 4.9616, Rotation2d.fromRadians(-1.8326))
    );
    public static final ChoreoTraj DepotIntake_RED = new ChoreoTraj(
        "DepotIntake_RED",
        OptionalInt.empty(),
        4.5751,
        new Pose2d(0.54124, 7.4, Rotation2d.fromRadians(-1.8326)),
        new Pose2d(0.54124, 4.9616, Rotation2d.fromRadians(-1.8326))
    );
    public static final ChoreoTraj DepotToLeftClimb_BLUE = new ChoreoTraj(
        "DepotToLeftClimb_BLUE",
        OptionalInt.empty(),
        2.91091,
        new Pose2d(1.0858, 5.9692, Rotation2d.fromRadians(1.5708)),
        new Pose2d(1.0788, 4.4938, Rotation2d.fromRadians(1.5708))
    );
    public static final ChoreoTraj DepotToLeftClimb_RED = new ChoreoTraj(
        "DepotToLeftClimb_RED",
        OptionalInt.empty(),
        2.91091,
        new Pose2d(1.0858, 5.9692, Rotation2d.fromRadians(1.5708)),
        new Pose2d(1.0788, 4.4938, Rotation2d.fromRadians(1.5708))
    );
    public static final ChoreoTraj LeftBumpToDepotPartial_BLUE = new ChoreoTraj(
        "LeftBumpToDepotPartial_BLUE",
        OptionalInt.empty(),
        2.33346,
        new Pose2d(2.66764, 6.03649, Rotation2d.fromRadians(3.14159)),
        new Pose2d(1.0858, 5.9692, Rotation2d.fromRadians(3.14159))
    );
    public static final ChoreoTraj LeftBumpToDepotPartial_RED = new ChoreoTraj(
        "LeftBumpToDepotPartial_RED",
        OptionalInt.empty(),
        2.33346,
        new Pose2d(2.66764, 6.03649, Rotation2d.fromRadians(3.14159)),
        new Pose2d(1.0858, 5.9692, Rotation2d.fromRadians(3.14159))
    );
    public static final ChoreoTraj LeftBumpToDepot_BLUE = new ChoreoTraj(
        "LeftBumpToDepot_BLUE",
        OptionalInt.empty(),
        2.24906,
        new Pose2d(3.58204, 6.03649, Rotation2d.fromRadians(3.14159)),
        new Pose2d(1.0858, 5.9692, Rotation2d.fromRadians(3.14159))
    );
    public static final ChoreoTraj LeftBumpToDepot_RED = new ChoreoTraj(
        "LeftBumpToDepot_RED",
        OptionalInt.empty(),
        2.24906,
        new Pose2d(3.58204, 6.03649, Rotation2d.fromRadians(3.14159)),
        new Pose2d(1.0858, 5.9692, Rotation2d.fromRadians(3.14159))
    );
    public static final ChoreoTraj LeftHubToClimb_BLUE = new ChoreoTraj(
        "LeftHubToClimb_BLUE",
        OptionalInt.empty(),
        1.84264,
        new Pose2d(3.57885, 4.18384, Rotation2d.fromRadians(3.14159)),
        new Pose2d(1.0788, 4.9, Rotation2d.fromRadians(1.5708))
    );
    public static final ChoreoTraj LeftHubToClimb_RED = new ChoreoTraj(
        "LeftHubToClimb_RED",
        OptionalInt.empty(),
        1.84264,
        new Pose2d(3.57885, 4.18384, Rotation2d.fromRadians(3.14159)),
        new Pose2d(1.0788, 4.9, Rotation2d.fromRadians(1.5708))
    );
    public static final ChoreoTraj LeftHubToDepot_BLUE = new ChoreoTraj(
        "LeftHubToDepot_BLUE",
        OptionalInt.empty(),
        2.76211,
        new Pose2d(3.57885, 4.18384, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.54124, 7.4, Rotation2d.fromRadians(-1.8326))
    );
    public static final ChoreoTraj LeftHubToDepot_BLUE$0 = new ChoreoTraj(
        "LeftHubToDepot_BLUE",
        OptionalInt.of(0),
        0.83507,
        new Pose2d(3.57885, 4.18384, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.99769, 5.32509, Rotation2d.fromRadians(-2.83767))
    );
    public static final ChoreoTraj LeftHubToDepot_BLUE$1 = new ChoreoTraj(
        "LeftHubToDepot_BLUE",
        OptionalInt.of(1),
        1.9270399999999999,
        new Pose2d(2.99769, 5.32509, Rotation2d.fromRadians(-2.83767)),
        new Pose2d(0.54124, 7.4, Rotation2d.fromRadians(-1.8326))
    );
    public static final ChoreoTraj LeftHubToDepot_RED = new ChoreoTraj(
        "LeftHubToDepot_RED",
        OptionalInt.empty(),
        2.76211,
        new Pose2d(3.57885, 4.18384, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.54124, 7.4, Rotation2d.fromRadians(-1.8326))
    );
    public static final ChoreoTraj LeftHubToDepot_RED$0 = new ChoreoTraj(
        "LeftHubToDepot_RED",
        OptionalInt.of(0),
        0.83507,
        new Pose2d(3.57885, 4.18384, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.99769, 5.32509, Rotation2d.fromRadians(-2.83767))
    );
    public static final ChoreoTraj LeftHubToDepot_RED$1 = new ChoreoTraj(
        "LeftHubToDepot_RED",
        OptionalInt.of(1),
        1.9270399999999999,
        new Pose2d(2.99769, 5.32509, Rotation2d.fromRadians(-2.83767)),
        new Pose2d(0.54124, 7.4, Rotation2d.fromRadians(-1.8326))
    );
    public static final ChoreoTraj LeftMiddleNZToShoot_BLUE = new ChoreoTraj(
        "LeftMiddleNZToShoot_BLUE",
        OptionalInt.empty(),
        2.67687,
        new Pose2d(7.80051, 4.92736, Rotation2d.fromRadians(-1.8326)),
        new Pose2d(2.92773, 7.12084, Rotation2d.fromRadians(0.5236))
    );
    public static final ChoreoTraj LeftMiddleNZToShoot_RED = new ChoreoTraj(
        "LeftMiddleNZToShoot_RED",
        OptionalInt.empty(),
        2.67687,
        new Pose2d(7.80051, 4.92736, Rotation2d.fromRadians(-1.8326)),
        new Pose2d(2.92773, 7.12084, Rotation2d.fromRadians(0.5236))
    );
    public static final ChoreoTraj LeftNZSecondPass = new ChoreoTraj(
        "LeftNZSecondPass",
        OptionalInt.empty(),
        4.52626,
        new Pose2d(8.4096, 4.92736, Rotation2d.fromRadians(-1.8326)),
        new Pose2d(2.92773, 7.12084, Rotation2d.fromRadians(-2.61799))
    );
    public static final ChoreoTraj LeftShootToDepot = new ChoreoTraj(
        "LeftShootToDepot",
        OptionalInt.empty(),
        6.19077,
        new Pose2d(2.92773, 7.12084, Rotation2d.fromRadians(0.5236)),
        new Pose2d(0.54124, 4.92584, Rotation2d.fromRadians(-1.8326))
    );
    public static final ChoreoTraj LeftShootToNZ_BLUE = new ChoreoTraj(
        "LeftShootToNZ_BLUE",
        OptionalInt.empty(),
        3.3001,
        new Pose2d(2.92773, 7.12084, Rotation2d.fromRadians(0.5236)),
        new Pose2d(6.51379, 2.84431, Rotation2d.fromRadians(-1.74404))
    );
    public static final ChoreoTraj LeftShootToNZ_RED = new ChoreoTraj(
        "LeftShootToNZ_RED",
        OptionalInt.empty(),
        3.3001,
        new Pose2d(2.92773, 7.12084, Rotation2d.fromRadians(0.5236)),
        new Pose2d(6.51379, 2.84431, Rotation2d.fromRadians(-1.74404))
    );
    public static final ChoreoTraj LeftTrenchToFarNZ = new ChoreoTraj(
        "LeftTrenchToFarNZ",
        OptionalInt.empty(),
        4.05553,
        new Pose2d(4.47611, 7.44373, Rotation2d.fromRadians(3.14159)),
        new Pose2d(8.4096, 4.92736, Rotation2d.fromRadians(-1.8326))
    );
    public static final ChoreoTraj LeftTrenchToNZ_BLUE = new ChoreoTraj(
        "LeftTrenchToNZ_BLUE",
        OptionalInt.empty(),
        3.90308,
        new Pose2d(4.47612, 7.44373, Rotation2d.fromRadians(3.14159)),
        new Pose2d(7.80051, 4.92736, Rotation2d.fromRadians(-1.8326))
    );
    public static final ChoreoTraj LeftTrenchToNZ_RED = new ChoreoTraj(
        "LeftTrenchToNZ_RED",
        OptionalInt.empty(),
        3.90308,
        new Pose2d(4.47612, 7.44373, Rotation2d.fromRadians(3.14159)),
        new Pose2d(7.80051, 4.92736, Rotation2d.fromRadians(-1.8326))
    );
    public static final ChoreoTraj MiddleNZToLeftClimb_BLUE = new ChoreoTraj(
        "MiddleNZToLeftClimb_BLUE",
        OptionalInt.empty(),
        3.67574,
        new Pose2d(7.80051, 4.92736, Rotation2d.fromRadians(-1.8326)),
        new Pose2d(1.0788, 4.9, Rotation2d.fromRadians(1.5708))
    );
    public static final ChoreoTraj MiddleNZToLeftClimb_RED = new ChoreoTraj(
        "MiddleNZToLeftClimb_RED",
        OptionalInt.empty(),
        3.67574,
        new Pose2d(7.80051, 4.92736, Rotation2d.fromRadians(-1.8326)),
        new Pose2d(1.0788, 4.9, Rotation2d.fromRadians(1.5708))
    );
    public static final ChoreoTraj MiddleNZToRightClimb_BLUE = new ChoreoTraj(
        "MiddleNZToRightClimb_BLUE",
        OptionalInt.empty(),
        3.47384,
        new Pose2d(7.77511, 3.26376, Rotation2d.fromRadians(1.8326)),
        new Pose2d(1.62441, 2.29999, Rotation2d.fromRadians(-1.5708))
    );
    public static final ChoreoTraj MiddleNZToRightClimb_RED = new ChoreoTraj(
        "MiddleNZToRightClimb_RED",
        OptionalInt.empty(),
        3.47384,
        new Pose2d(7.77511, 3.26376, Rotation2d.fromRadians(1.8326)),
        new Pose2d(1.62441, 2.29999, Rotation2d.fromRadians(-1.5708))
    );
    public static final ChoreoTraj OutpostToRightClimb_BLUE = new ChoreoTraj(
        "OutpostToRightClimb_BLUE",
        OptionalInt.empty(),
        2.21989,
        new Pose2d(0.44334, 0.774, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(1.0407, 2.65, Rotation2d.fromRadians(-1.5708))
    );
    public static final ChoreoTraj OutpostToRightClimb_RED = new ChoreoTraj(
        "OutpostToRightClimb_RED",
        OptionalInt.empty(),
        2.21989,
        new Pose2d(0.44334, 0.774, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(1.0407, 2.65, Rotation2d.fromRadians(-1.5708))
    );
    public static final ChoreoTraj RightHubToClimb_BLUE = new ChoreoTraj(
        "RightHubToClimb_BLUE",
        OptionalInt.empty(),
        2.12884,
        new Pose2d(3.57885, 3.88926, Rotation2d.fromRadians(3.14159)),
        new Pose2d(1.0407, 2.65, Rotation2d.fromRadians(-1.5708))
    );
    public static final ChoreoTraj RightHubToClimb_RED = new ChoreoTraj(
        "RightHubToClimb_RED",
        OptionalInt.empty(),
        2.12884,
        new Pose2d(3.57885, 3.88926, Rotation2d.fromRadians(3.14159)),
        new Pose2d(1.0407, 2.65, Rotation2d.fromRadians(-1.5708))
    );
    public static final ChoreoTraj RightMiddleNZToOutpost_BLUE = new ChoreoTraj(
        "RightMiddleNZToOutpost_BLUE",
        OptionalInt.empty(),
        4.6237,
        new Pose2d(7.77511, 3.26376, Rotation2d.fromRadians(1.8326)),
        new Pose2d(0.44334, 0.774, Rotation2d.fromRadians(-1.5708))
    );
    public static final ChoreoTraj RightMiddleNZToOutpost_BLUE$0 = new ChoreoTraj(
        "RightMiddleNZToOutpost_BLUE",
        OptionalInt.of(0),
        2.90487,
        new Pose2d(7.77511, 3.26376, Rotation2d.fromRadians(1.8326)),
        new Pose2d(2.0043, 1.0794, Rotation2d.fromRadians(-0.70863))
    );
    public static final ChoreoTraj RightMiddleNZToOutpost_BLUE$1 = new ChoreoTraj(
        "RightMiddleNZToOutpost_BLUE",
        OptionalInt.of(1),
        1.7188300000000005,
        new Pose2d(2.0043, 1.0794, Rotation2d.fromRadians(-0.70863)),
        new Pose2d(0.44334, 0.774, Rotation2d.fromRadians(-1.5708))
    );
    public static final ChoreoTraj RightMiddleNZToOutpost_RED = new ChoreoTraj(
        "RightMiddleNZToOutpost_RED",
        OptionalInt.empty(),
        4.6237,
        new Pose2d(7.77511, 3.26376, Rotation2d.fromRadians(1.8326)),
        new Pose2d(0.44334, 0.774, Rotation2d.fromRadians(-1.5708))
    );
    public static final ChoreoTraj RightMiddleNZToOutpost_RED$0 = new ChoreoTraj(
        "RightMiddleNZToOutpost_RED",
        OptionalInt.of(0),
        2.90487,
        new Pose2d(7.77511, 3.26376, Rotation2d.fromRadians(1.8326)),
        new Pose2d(2.0043, 1.0794, Rotation2d.fromRadians(-0.70863))
    );
    public static final ChoreoTraj RightMiddleNZToOutpost_RED$1 = new ChoreoTraj(
        "RightMiddleNZToOutpost_RED",
        OptionalInt.of(1),
        1.7188300000000005,
        new Pose2d(2.0043, 1.0794, Rotation2d.fromRadians(-0.70863)),
        new Pose2d(0.44334, 0.774, Rotation2d.fromRadians(-1.5708))
    );
    public static final ChoreoTraj RightMiddleNZToShoot_BLUE = new ChoreoTraj(
        "RightMiddleNZToShoot_BLUE",
        OptionalInt.empty(),
        2.87119,
        new Pose2d(7.77511, 3.26376, Rotation2d.fromRadians(1.8326)),
        new Pose2d(3.08013, 0.69012, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj RightMiddleNZToShoot_RED = new ChoreoTraj(
        "RightMiddleNZToShoot_RED",
        OptionalInt.empty(),
        2.87119,
        new Pose2d(7.77511, 3.26376, Rotation2d.fromRadians(1.8326)),
        new Pose2d(3.08013, 0.69012, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj RightShootToNZ_BLUE = new ChoreoTraj(
        "RightShootToNZ_BLUE",
        OptionalInt.empty(),
        3.28512,
        new Pose2d(3.08013, 0.69012, Rotation2d.fromRadians(0)),
        new Pose2d(6.67232, 3.29398, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj RightShootToNZ_RED = new ChoreoTraj(
        "RightShootToNZ_RED",
        OptionalInt.empty(),
        3.28512,
        new Pose2d(3.08013, 0.69012, Rotation2d.fromRadians(0)),
        new Pose2d(6.67232, 3.29398, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj RightTrenchToClimb_BLUE = new ChoreoTraj(
        "RightTrenchToClimb_BLUE",
        OptionalInt.empty(),
        3.75582,
        new Pose2d(3.58204, 2.03271, Rotation2d.fromRadians(3.14159)),
        new Pose2d(1.0407, 2.9572, Rotation2d.fromRadians(-1.5708))
    );
    public static final ChoreoTraj RightTrenchToClimb_RED = new ChoreoTraj(
        "RightTrenchToClimb_RED",
        OptionalInt.empty(),
        3.75582,
        new Pose2d(3.58204, 2.03271, Rotation2d.fromRadians(3.14159)),
        new Pose2d(1.0407, 2.9572, Rotation2d.fromRadians(-1.5708))
    );
    public static final ChoreoTraj RightTrenchToNZ_BLUE = new ChoreoTraj(
        "RightTrenchToNZ_BLUE",
        OptionalInt.empty(),
        3.88264,
        new Pose2d(4.47612, 0.62547, Rotation2d.fromRadians(3.14159)),
        new Pose2d(7.77511, 3.26376, Rotation2d.fromRadians(1.8326))
    );
    public static final ChoreoTraj RightTrenchToNZ_RED = new ChoreoTraj(
        "RightTrenchToNZ_RED",
        OptionalInt.empty(),
        3.88264,
        new Pose2d(4.47612, 0.62547, Rotation2d.fromRadians(3.14159)),
        new Pose2d(7.77511, 3.26376, Rotation2d.fromRadians(1.8326))
    );
    public static final ChoreoTraj WarmUpStraight = new ChoreoTraj(
        "WarmUpStraight",
        OptionalInt.empty(),
        4.50092,
        new Pose2d(0, 0, Rotation2d.fromRadians(0)),
        new Pose2d(2, 0, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj WarmUpTurn = new ChoreoTraj(
        "WarmUpTurn",
        OptionalInt.empty(),
        1.73249,
        new Pose2d(0, 0, Rotation2d.fromRadians(0)),
        new Pose2d(0, 0, Rotation2d.fromRadians(0))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
        Map.entry("DepotIntakeToClimb_BLUE", DepotIntakeToClimb_BLUE),
        Map.entry("DepotIntakeToClimb_RED", DepotIntakeToClimb_RED),
        Map.entry("DepotIntake_BLUE", DepotIntake_BLUE),
        Map.entry("DepotIntake_RED", DepotIntake_RED),
        Map.entry("DepotToLeftClimb_BLUE", DepotToLeftClimb_BLUE),
        Map.entry("DepotToLeftClimb_RED", DepotToLeftClimb_RED),
        Map.entry("LeftBumpToDepotPartial_BLUE", LeftBumpToDepotPartial_BLUE),
        Map.entry("LeftBumpToDepotPartial_RED", LeftBumpToDepotPartial_RED),
        Map.entry("LeftBumpToDepot_BLUE", LeftBumpToDepot_BLUE),
        Map.entry("LeftBumpToDepot_RED", LeftBumpToDepot_RED),
        Map.entry("LeftHubToClimb_BLUE", LeftHubToClimb_BLUE),
        Map.entry("LeftHubToClimb_RED", LeftHubToClimb_RED),
        Map.entry("LeftHubToDepot_BLUE", LeftHubToDepot_BLUE),
        Map.entry("LeftHubToDepot_BLUE$0", LeftHubToDepot_BLUE$0),
        Map.entry("LeftHubToDepot_BLUE$1", LeftHubToDepot_BLUE$1),
        Map.entry("LeftHubToDepot_RED", LeftHubToDepot_RED),
        Map.entry("LeftHubToDepot_RED$0", LeftHubToDepot_RED$0),
        Map.entry("LeftHubToDepot_RED$1", LeftHubToDepot_RED$1),
        Map.entry("LeftMiddleNZToShoot_BLUE", LeftMiddleNZToShoot_BLUE),
        Map.entry("LeftMiddleNZToShoot_RED", LeftMiddleNZToShoot_RED),
        Map.entry("LeftNZSecondPass", LeftNZSecondPass),
        Map.entry("LeftShootToDepot", LeftShootToDepot),
        Map.entry("LeftShootToNZ_BLUE", LeftShootToNZ_BLUE),
        Map.entry("LeftShootToNZ_RED", LeftShootToNZ_RED),
        Map.entry("LeftTrenchToFarNZ", LeftTrenchToFarNZ),
        Map.entry("LeftTrenchToNZ_BLUE", LeftTrenchToNZ_BLUE),
        Map.entry("LeftTrenchToNZ_RED", LeftTrenchToNZ_RED),
        Map.entry("MiddleNZToLeftClimb_BLUE", MiddleNZToLeftClimb_BLUE),
        Map.entry("MiddleNZToLeftClimb_RED", MiddleNZToLeftClimb_RED),
        Map.entry("MiddleNZToRightClimb_BLUE", MiddleNZToRightClimb_BLUE),
        Map.entry("MiddleNZToRightClimb_RED", MiddleNZToRightClimb_RED),
        Map.entry("OutpostToRightClimb_BLUE", OutpostToRightClimb_BLUE),
        Map.entry("OutpostToRightClimb_RED", OutpostToRightClimb_RED),
        Map.entry("RightHubToClimb_BLUE", RightHubToClimb_BLUE),
        Map.entry("RightHubToClimb_RED", RightHubToClimb_RED),
        Map.entry("RightMiddleNZToOutpost_BLUE", RightMiddleNZToOutpost_BLUE),
        Map.entry("RightMiddleNZToOutpost_BLUE$0", RightMiddleNZToOutpost_BLUE$0),
        Map.entry("RightMiddleNZToOutpost_BLUE$1", RightMiddleNZToOutpost_BLUE$1),
        Map.entry("RightMiddleNZToOutpost_RED", RightMiddleNZToOutpost_RED),
        Map.entry("RightMiddleNZToOutpost_RED$0", RightMiddleNZToOutpost_RED$0),
        Map.entry("RightMiddleNZToOutpost_RED$1", RightMiddleNZToOutpost_RED$1),
        Map.entry("RightMiddleNZToShoot_BLUE", RightMiddleNZToShoot_BLUE),
        Map.entry("RightMiddleNZToShoot_RED", RightMiddleNZToShoot_RED),
        Map.entry("RightShootToNZ_BLUE", RightShootToNZ_BLUE),
        Map.entry("RightShootToNZ_RED", RightShootToNZ_RED),
        Map.entry("RightTrenchToClimb_BLUE", RightTrenchToClimb_BLUE),
        Map.entry("RightTrenchToClimb_RED", RightTrenchToClimb_RED),
        Map.entry("RightTrenchToNZ_BLUE", RightTrenchToNZ_BLUE),
        Map.entry("RightTrenchToNZ_RED", RightTrenchToNZ_RED),
        Map.entry("WarmUpStraight", WarmUpStraight),
        Map.entry("WarmUpTurn", WarmUpTurn)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
// spotless:on
